# Generated by Django 5.2.7 on 2025-11-02 23:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(blank=True, max_length=100, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('engine', models.CharField(blank=True, max_length=200, null=True)),
                ('transmission', models.CharField(blank=True, max_length=100, null=True)),
                ('train', models.CharField(blank=True, max_length=50, null=True)),
                ('exterior_color', models.CharField(max_length=50)),
                ('interior_color', models.CharField(max_length=50)),
                ('miles', models.IntegerField()),
                ('mpg', models.CharField(blank=True, max_length=50, null=True)),
                ('title_status', models.CharField(choices=[('LIMPO', 'Limpo'), ('SALVAGE', 'Salvage'), ('REBUILT', 'Rebuilt'), ('OUTROS', 'Outros')], default='LIMPO', max_length=20)),
                ('title_problem_description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('FALTA_INSPECAO', 'Falta Inspeção'), ('DISPONIVEL', 'Disponível'), ('VENDIDO', 'Vendido'), ('MECANICA', 'Em Mecânica')], default='FALTA_INSPECAO', max_length=20)),
                ('general_notes', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='garage.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NAO_RESPONDIDO', 'Não Respondido')], default='NAO_RESPONDIDO', max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.inspectiontemplate')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='garage.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'template')},
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='vehicles/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='garage.vehicle')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='garage.vehicleinspection')),
            ],
        ),
    ]
