# Generated by Django 5.2.7 on 2025-11-07 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_photo_public_id_alter_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='public_id',
            new_name='cloudinary_public_id',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='image_url',
        ),
    ]
