# Generated by Django 5.2.8 on 2025-11-09 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0003_rename_public_id_photo_cloudinary_public_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="google_drive_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID do Google Drive"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_photos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Enviado por",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("SEDAN", "Sedan"),
                    ("SUV", "SUV"),
                    ("TRUCK", "Truck"),
                    ("COUPE", "Coupe"),
                    ("HATCHBACK", "Hatchback"),
                    ("VAN", "Van"),
                    ("WAGON", "Wagon"),
                    ("CONVERTIBLE", "Conversível"),
                    ("OUTROS", "Outros"),
                ],
                default="OUTROS",
                max_length=20,
                verbose_name="Tipo de Carro",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_vehicles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="interior_color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
