# Generated by Django 5.2.8 on 2025-11-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0004_photo_google_drive_id_photo_uploaded_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="cloudinary_public_id",
        ),
        migrations.AlterField(
            model_name="photo",
            name="image_url",
            field=models.URLField(max_length=500, verbose_name="URL do Google Drive"),
        ),
    ]
